framework:
    messenger:
        default_bus: messenger.bus
        buses:
            messenger.bus:
                default_middleware: true
                middleware:
                    - 'middleware.doctrine.transactional'
                    - 'middleware.exception.catcher'
