services:
  repository.dbal.connection:
    class: Doctrine\DBAL\Connection
    factory: 'Doctrine\DBAL\DriverManager::getConnection'
    arguments:
      - url: '%db_url%'
        driver: 'pdo_pgsql'

  Doctrine\DBAL\Connection:
    alias: repository.dbal.connection

  repository.dbal.migration:
    class: AdnanMula\ClockInBot\Infrastructure\Persistence\Doctrine\Repository\DbalMigration
    arguments:
      - '@repository.dbal.connection'

  repository.dbal.migration.v001:
    class: AdnanMula\ClockInBot\Migrations\Postgresql\V001
    parent: 'repository.dbal.migration'

  repository.dbal.base:
    class: AdnanMula\ClockInBot\Infrastructure\Persistence\Doctrine\Repository\DbalRepository
    arguments:
      - '@repository.dbal.connection'

  repository.dbal.fixture.base:
    class: AdnanMula\ClockInBot\Infrastructure\Persistence\Doctrine\Repository\DbalRepository
    arguments:
      - '@repository.dbal.connection'

  repository.dbal.fixture.user:
    class: AdnanMula\ClockInBot\Infrastructure\Fixtures\User\UserFixtures
    parent: 'repository.dbal.fixture.base'
    arguments:
      - '@repository.dbal.connection'

  repository.dbal.fixture.registry:
    class: AdnanMula\ClockInBot\Infrastructure\Fixtures\FixturesRegistry
    arguments:
      - '@repository.dbal.fixture.user'
