parameters:
  telegram_commands:
#   Commands
    AdnanMula\ClockInBot\Application\Command\User\Register\UserRegisterCommand:
      - 'registrar'
      - 'register'
    AdnanMula\ClockInBot\Application\Command\User\SetUp\UserSetUpCommand:
      - 'setup'
      - 'configuracion'
    AdnanMula\ClockInBot\Application\Command\User\ManualClockIn\UserManualClockInCommand:
      - 'picar'
      - 'fichar'
      - 'clockin'
#   Query
    AdnanMula\ClockInBot\Application\Query\User\GetClockIns\GetClockInsQuery:
      - 'fichajes'
      - 'picajes'
    AdnanMula\ClockInBot\Application\Query\User\GetConfig\GetConfigQuery:
      - 'setup'
      - 'configuracion'
