services:
  AdnanMula\ClockInBot\Domain\Model\User\UserRepository:
    class: AdnanMula\ClockInBot\Infrastructure\Persistence\Doctrine\Repository\User\UserDbalRepository
    parent: 'repository.dbal.base'

  AdnanMula\ClockInBot\Domain\Model\UserSettings\UserSettingsRepository:
    class: AdnanMula\ClockInBot\Infrastructure\Persistence\Doctrine\Repository\UserSettings\UserSettingsDbalRepository
    parent: 'repository.dbal.base'

  AdnanMula\ClockInBot\Domain\Model\UserSchedule\UserScheduleRepository:
    class: AdnanMula\ClockInBot\Infrastructure\Persistence\Doctrine\Repository\UserSchedule\UserScheduleDbalRepository
    parent: 'repository.dbal.base'

  AdnanMula\ClockInBot\Domain\Model\UserClientData\UserClientDataRepository:
    class: AdnanMula\ClockInBot\Infrastructure\Persistence\Doctrine\Repository\UserSchedule\UserScheduleDbalRepository
    parent: 'repository.dbal.base'