parameters:
    db_url: '%env(resolve:DATABASE_URL)%'

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    AdnanMula\ClockInBot\Application\:
        autowire: true
        autoconfigure: true
        resource: '../src/Application/{Command,Query}/*/*/*Handler.php'
        tags: [{ name: messenger.message_handler, bus: messenger.bus.command }]

    AdnanMula\ClockInBot\Domain\Service\:
        autowire: true
        autoconfigure: true
        resource: '../src/Domain/Service'

    AdnanMula\ClockInBot\Infrastructure\Service\:
        autowire: true
        autoconfigure: true
        resource: '../src/Infrastructure/Service'
        bind:
            string $botToken: '%env(TELEGRAM_TOKEN)%'

    AdnanMula\ClockInBot\Infrastructure\Persistence\Doctrine\Repository\:
        autowire: true
        autoconfigure: true
        resource: '../src/Infrastructure/Persistence/Doctrine/Repository'

    AdnanMula\ClockInBot\Entrypoint\Command\:
        autowire: true
        autoconfigure: true
        resource: '../src/Entrypoint/Command'
        bind:
            array $telegramCommands: '%telegram_commands%'
            AdnanMula\ClockInBot\Infrastructure\Fixtures\FixturesRegistry $registry: '@repository.dbal.fixture.registry'
            AdnanMula\ClockInBot\Domain\Service\Persistence\Migration $migration: '@repository.dbal.migration.v001'

imports:
    - { resource: context/system/buses.yaml }
    - { resource: context/system/repository.yaml }
    - { resource: context/system/telegram_commands.yaml }
    - { resource: context/user/repository.yaml }
